// src/routes/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import LoadingCenter from '$lib/loading_center.svelte';
	import { invoke } from '@tauri-apps/api/tauri';
	import { onMount } from 'svelte';

	onMount(async () => {
		let have_account = (await invoke('have_account')) as boolean;

		if (!have_account) {
			goto('/welcom');
		} else {
			goto('/main');
		}
	});
</script>

<LoadingCenter />

// src/routes/index.tsx
import { useNavigate } from 'solid-start';
import { have_account } from '~/ts/api-tauri';

export default function Index() {
	const navigate = useNavigate();

	have_account().then((have_account) => {
		if (have_account) {
			navigate('/main');
		} else {
			navigate('/welcom');
		}
	});

	return <main></main>;
}
