// src/routes/welcom.tsx
import { Component } from 'solid-js';
import { Title, useNavigate } from 'solid-start';
import { Link } from '~/components/small/link';
import { BadgeVersion } from '~/components/small/badge_version';

const Logo: Component = () => {
	return (
		<div class="flex flex-col items-center">
			<img src="index/lock.svg" class="h-64 w-64 py-4" />

			<h1 class="text-5xl font-bold">Security chat</h1>
		</div>
	);
};

export default function Index() {
	const navigate = useNavigate();

	return (
		<main>
			<Title>Добро пожаловать!</Title>

			<div class="hero min-h-screen text-center">
				<div class="max-w-md">
					<Logo />

					<p class="py-6">
						Универсальный чат который даёт вам <strong>приватность</strong>,{' '}
						<strong>анонимность</strong> c{' '}
						<Link
							text="открытым исходным кодом"
							link="https://github.com/CryptoGladi/security-chat"
						/>
					</p>
					<button
						class="btn btn-primary"
						onClick={() => {
							navigate('/registration');
						}}
					>
						Начать использование
					</button>
				</div>
			</div>

			<BadgeVersion />
		</main>
	);
}

// src/routes/welcom/+page.svelte
<script lang="ts">
	import RegistrationModal from './registration_modal.svelte';
	import VscGithubInverted from 'svelte-icons-pack/vsc/VscGithubInverted';
	import Icon from 'svelte-icons-pack/Icon.svelte';
	import { invoke } from '@tauri-apps/api/tauri';

	let registration_modal: HTMLDialogElement;
</script>

<div class="hero-content text-center hero min-h-screen">
	<div class="max-w-md">
		<h1 class="text-5xl font-bold">Добро пожаловать</h1>
		<div class="py-6">
			<p>
				<strong>Security chat</strong> - это универсальный чат который даёт вам приватность и анонимность
			</p>
			<p>Для начала использования программы вам завершить её настройку</p>
		</div>

		<button
			class="btn btn-primary"
			on:click={() => {
				registration_modal.showModal();
			}}>Начать</button
		>

		<dialog bind:this={registration_modal} class="modal">
			<RegistrationModal />
		</dialog>
	</div>
</div>

<div class="bottom-0 right-0 flex space-x-2 px-1 py-1 w-10" style="position: absolute;">
	<div
		class="w-full h-full"
		on:click={() => invoke('open', { path: 'https://github.com/CryptoGladi/security-chat' })}
	>
		<Icon src={VscGithubInverted} className="w-full h-full" color="white" />
	</div>
</div>
